[package]
name = "vulkan_compute"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.37.0", default-features = false, features = ["linked"] }
log = "0.4"
rand = "0.8.5"
simplelog = "0.12.0"

[build-dependencies]
shaderc = "0.8.1"
